export { default as Footer } from "./Footer"
export { default as Header } from "./Header"
export { default as Hero } from "./Hero"
export { default as MovingLines } from "./MovingLines"
export { default as TopSection } from "./TopSection"
export { default as WhoAmi } from "./WhoAmi"
export { default as Works } from "./Works"